;; -*- mode: emacs-lisp; lexical-binding: t -*-
;; This file is loaded by Spacemacs at startup.
;; It must be stored in your home directory.

;; NOTE: DO NOT EDIT THIS FILE DIRECTLY!!!
;; This file is autogenerated from ~dotspacemacs.org~, and changes should be made there, then the file tangled.
(defun dotspacemacs/layers ()
  "Layer configuration:
This function should only modify configuration layer settings."
  (setq-default
   ;; Base distribution to use. This is a layer contained in the directory
   ;; `+distribution'. For now available distributions are `spacemacs-base'
   ;; or `spacemacs'. (default 'spacemacs)
   dotspacemacs-distribution 'spacemacs

   ;; Lazy installation of layers (i.e. layers are installed only when a file
   ;; with a supported type is opened). Possible values are `all', `unused'
   ;; and `nil'. `unused' will lazy install only unused layers (i.e. layers
   ;; not listed in variable `dotspacemacs-configuration-layers'), `all' will
   ;; lazy install any layer that support lazy installation even the layers
   ;; listed in `dotspacemacs-configuration-layers'. `nil' disable the lazy
   ;; installation feature and you have to explicitly list a layer in the
   ;; variable `dotspacemacs-configuration-layers' to install it.
   ;; (default 'unused)
   dotspacemacs-enable-lazy-installation 'unused

   ;; If non-nil then Spacemacs will ask for confirmation before installing
   ;; a layer lazily. (default t)
   dotspacemacs-ask-for-lazy-installation t

   ;; List of additional paths where to look for configuration layers.
   ;; Paths must have a trailing slash (i.e. `~/.mycontribs/')
   dotspacemacs-configuration-layer-path '()

   ;; List of configuration layers to load.
   dotspacemacs-configuration-layers
   '(
     (auto-completion :variables
                      auto-completion-return-key-behavior 'complete
                      auto-completion-tab-key-behavior 'cycle
                      auto-completion-minimum-prefix-length 2
                      auto-completion-complete-with-key-sequence "jk"
                      auto-completion-complete-with-key-sequence-delay 0.1
                      auto-completion-idle-delay 0.0
                      auto-completion-private-snippets-directory nil
                      auto-completion-enable-snippets-in-popup t
                      auto-completion-enable-help-tooltip t
                      auto-completion-use-company-box t
                      auto-completion-use-company-posframe t
                      auto-completion-enable-sort-by-usage t
     
                      spacemacs-default-company-backends '(company-files company-capf company-keywords))
     
     (colors :variables
             colors-colorize-identifiers 'variables)
     emoji
     evil-better-jumper
     helm
     (org :variables
          org-enable-roam-support t
          org-enable-roam-ui t
          org-enable-sticky-header t
          org-enable-transclusion-support t
          )
     (osx :variables
          osx-command-as nil)
     spacemacs-modeline
     spacemacs-org
     spacemacs-navigation
     syntax-checking
     theming
     themes-megapack
     (treemacs :variables
               treemacs-sorting 'alphabetic-asc
               ;; treemacs-use-follow-mode 'tag
               treemacs-use-git-mode 'deferred
               treemacs-use-scope-type 'Perspectives
               treemacs-use-filewatch-mode t)
     rust
     (javascript :variables
                 javascript-repl 'nodejs
                 javascript-fmt-on-save t
                 node-add-modules-path t
                 javascript-fmt-tool 'prettier) ;; includes Coffeescript support
     (typescript :variables
                 typescript-backend 'tide
                 typescript-linter 'eslint
                 tide-tsserver-executable "/Users/rodk/.asdf/installs/nodejs/14.19.0/.npm/bin/tsserver")
     (lua :variables
          lua-backend 'lsp-emmy
          lua-lsp-emmy-jar-path "~/.emacs.d/EmmyLua-LS-all.jar" ; default path
          lua-lsp-emmy-java-path "java"                         ; default path
          lua-lsp-emmy-enable-file-watchers t)                  ; enabled default
     (python :variables
             python-fill-column 99
             python-test-runner 'pytest
             python-backend 'lsp
             python-lsp-server 'pyright
             python-formatter 'black
             python-format-on-save t
             )
     emacs-lisp
     prettier
     react
     (mermaid :variables
              ob-mermaid-cli-path "/Users/rodk/personal/org-files/node_modules/.bin/mmdc")
     html
     markdown
     (yaml :variables
           yaml-enable-lsp t)
     csv
     pdf
     ansible
     cmake
     restclient
     (lsp :variables
          lsp-file-watch-threshold 2000
          lsp-navigation 'peek
          lsp-headerline-breadcrumb-enable t
          lsp-headerline-breadcrumb-segments '(path-up-to-project file symbols)
          )
     ;; (tree-sitter :variables
     ;;              spacemacs-tree-sitter-hl-black-list '(js2-mode rjsx-mode)
     ;;              tree-sitter-syntax-highlight-enable t
     ;;              tree-sitter-fold-enable t
     ;;              tree-sitter-fold-indicators-enable nil)
     pass
     
     ;; github-copilot
     
     chrome
     docker
     git
     (wakatime :variables
               wakatime-api-key "REDACTED_WAKATIME_KEY"
               wakatime-cli-path "/opt/homebrew/bin/wakatime-cli")
     
     (elfeed :variables
             elfeed-db-directory "~/personal/org-files/elfeed-db"
             rmh-elfeed-org-files (list "~/personal/org-files/elfeed.org")) 
     ;; (compleseus :variables
     ;;             compleseus-enable-marginalia t  ;; Enable annotations
     ;;             compleseus-enable-consult t     ;; Enable Consult for advanced commands
     ;;             compleseus-enable-orderless t   ;; Use Orderless for flexible matching
     ;;             compleseus-enable-corfu t       ;; Enable Corfu for completion-at-point
     ;;             compleseus-corfu-auto t         ;; Auto popup completions in Corfu
     ;;             compleseus-enable-embark t)     ;; Enable Embark for candidate actions
     
     bm
     command-log
     copy-as-format
     eww
     helpful
     ibuffer
     (search-engine)
     (spell-checking :variables
                     spell-checking-enable-by-default nil
                     enable-flyspell-auto-completion t)
     (version-control :variables
                      version-control-diff-side 'left)
     
     (tree-sitter :variables
                  spacemacs-tree-sitter-hl-black-list '(js2-mode rjsx-mode)
                  tree-sitter-syntax-highlight-enable t
                  tree-sitter-fold-enable t
                  tree-sitter-fold-indicators-enable nil)
     (shell :variables
            shell-default-shell 'vterm
            shell-default-term-shell "/bin/zsh"
            spacemacs-vterm-history-file-location "~/.zsh_history"
            shell-default-height 50
            shell-default-position 'right
            shell-enable-smart-eshell nil
            shell-default-full-span nil
            close-window-with-terminal t)
     ;; private layers
     rk-layout
     )


   ;; List of additional packages that will be installed without being wrapped
   ;; in a layer (generally the packages are installed only and should still be
   ;; loaded using load/require/use-package in the user-config section below in
   ;; this file). If you need some configuration for these packages, then
   ;; consider creating a layer. You can also put the configuration in
   ;; `dotspacemacs/user-config'. To use a local version of a package, use the
   ;; `:location' property: '(your-package :location "~/path/to/your-package/")
   ;; Also include the dependencies as they will not be resolved automatically.
   dotspacemacs-additional-packages '(
                                      fold-this
                                      evil-easymotion
                                      fira-code-mode
                                      highlight-indent-guides
                                      ef-themes
                                      sqlite3
                                      all-the-icons
                                      mermaid-mode
                                      org-roam-bibtex
                                      org-noter
                                      org-noter-pdftools
                                      hyperbole
                                      ;; (chatgpt :location (recipe
                                      ;;                     :fetcher github
                                      ;;                     :repo "joshcho/ChatGPT.el"))
                                      gptel
                                      (gptel-extensions :location "/Users/rodk//.emacs.d/private/gptel-extensions.el/")
                                      
                                      direnv
                                      pinboard
                                      ;; (copilot :location (recipe
                                      ;;                     :fetcher github
                                      ;;                     :repo "zerolfx/copilot.el"
                                      ;;                     :files ("*.el" "dist")))
                                      atomic-chrome
                                      editorconfig
                                      fold-this
                                      jira-markup-mode
                                      keychain-environment
                                      sicp
                                      wsd-mode
                                      yasnippet-snippets
                                      )

   ;; A list of packages that cannot be updated.
   dotspacemacs-frozen-packages '()

   ;; A list of packages that will not be installed and loaded.
   dotspacemacs-excluded-packages '(
                                    )

   ;; Defines the behaviour of Spacemacs when installing packages.
   ;; Possible values are `used-only', `used-but-keep-unused' and `all'.
   ;; `used-only' installs only explicitly used packages and deletes any unused
   ;; packages as well as their unused dependencies. `used-but-keep-unused'
   ;; installs only the used packages but won't delete unused ones. `all'
   ;; installs *all* packages supported by Spacemacs and never uninstalls them.
   ;; (default is `used-only')
   dotspacemacs-install-packages 'used-only))
(defun dotspacemacs/init ()
  "Initialization:
This function is called at the very beginning of Spacemacs startup,
before layer configuration.
It should only modify the values of Spacemacs settings."
  ;; This setq-default sexp is an exhaustive list of all the supported
  ;; spacemacs settings.
  (setq-default
   ;; If non-nil then enable support for the portable dumper. You'll need to
   ;; compile Emacs 27 from source following the instructions in file
   ;; EXPERIMENTAL.org at to root of the git repository.
   ;; WARNING: pdumper does not work with Native Compilation, so it's disabled
   ;; regardless of the following setting when native compilation is in effect.
   ;; (default nil)
   dotspacemacs-enable-emacs-pdumper nil

   ;; Name of executable file pointing to emacs 27+. This executable must be
   ;; in your PATH.
   ;; (default "emacs")
   dotspacemacs-emacs-pdumper-executable-file "emacs"

   ;; Name of the Spacemacs dump file. This is the file will be created by the
   ;; portable dumper in the cache directory under dumps sub-directory.
   ;; To load it when starting Emacs add the parameter `--dump-file'
   ;; when invoking Emacs 27.1 executable on the command line, for instance:
   ;;   ./emacs --dump-file=$HOME/.emacs.d/.cache/dumps/spacemacs-27.1.pdmp
   ;; (default (format "spacemacs-%s.pdmp" emacs-version))
   dotspacemacs-emacs-dumper-dump-file (format "spacemacs-%s.pdmp" emacs-version)

   ;; If non-nil ELPA repositories are contacted via HTTPS whenever it's
   ;; possible. Set it to nil if you have no way to use HTTPS in your
   ;; environment, otherwise it is strongly recommended to let it set to t.
   ;; This variable has no effect if Emacs is launched with the parameter
   ;; `--insecure' which forces the value of this variable to nil.
   ;; (default t)
   dotspacemacs-elpa-https t

   ;; Maximum allowed time in seconds to contact an ELPA repository.
   ;; (default 5)
   dotspacemacs-elpa-timeout 5

   ;; Set `gc-cons-threshold' and `gc-cons-percentage' when startup finishes.
   ;; This is an advanced option and should not be changed unless you suspect
   ;; performance issues due to garbage collection operations.
   ;; (default '(100000000 0.1))
   dotspacemacs-gc-cons '(100000000 0.1)

   ;; Set `read-process-output-max' when startup finishes.
   ;; This defines how much data is read from a foreign process.
   ;; Setting this >= 1 MB should increase performance for lsp servers
   ;; in emacs 27.
   ;; (default (* 1024 1024))
   dotspacemacs-read-process-output-max (* 16 1024 1024)

   ;; If non-nil then Spacelpa repository is the primary source to install
   ;; a locked version of packages. If nil then Spacemacs will install the
   ;; latest version of packages from MELPA. Spacelpa is currently in
   ;; experimental state please use only for testing purposes.
   ;; (default nil)
   dotspacemacs-use-spacelpa nil

   ;; If non-nil then verify the signature for downloaded Spacelpa archives.
   ;; (default t)
   dotspacemacs-verify-spacelpa-archives t

   ;; If non-nil then spacemacs will check for updates at startup
   ;; when the current branch is not `develop'. Note that checking for
   ;; new versions works via git commands, thus it calls GitHub services
   ;; whenever you start Emacs. (default nil)
   dotspacemacs-check-for-update nil

   ;; If non-nil, a form that evaluates to a package directory. For example, to
   ;; use different package directories for different Emacs versions, set this
   ;; to `emacs-version'. (default 'emacs-version)
   dotspacemacs-elpa-subdirectory 'emacs-version

   ;; One of `vim', `emacs' or `hybrid'.
   ;; `hybrid' is like `vim' except that `insert state' is replaced by the
   ;; `hybrid state' with `emacs' key bindings. The value can also be a list
   ;; with `:variables' keyword (similar to layers). Check the editing styles
   ;; section of the documentation for details on available variables.
   ;; (default 'vim)
   dotspacemacs-editing-style '(vim :variables
                                    vim-style-visual-line-move-text t
                                )

   ;; If non-nil show the version string in the Spacemacs buffer. It will
   ;; appear as (spacemacs version)@(emacs version)
   ;; (default t)
   dotspacemacs-startup-buffer-show-version t

   ;; Specify the startup banner. Default value is `official', it displays
   ;; the official spacemacs logo. An integer value is the index of text
   ;; banner, `random' chooses a random text banner in `core/banners'
   ;; directory. A string value must be a path to an image format supported
   ;; by your Emacs build.
   ;; If the value is nil then no banner is displayed. (default 'official)
   dotspacemacs-startup-banner 'random

   ;; Scale factor controls the scaling (size) of the startup banner. Default
   ;; value is `auto' for scaling the logo automatically to fit all buffer
   ;; contents, to a maximum of the full image height and a minimum of 3 line
   ;; heights. If set to a number (int or float) it is used as a constant
   ;; scaling factor for the default logo size.
   dotspacemacs-startup-banner-scale 'auto

   ;; List of items to show in startup buffer or an association list of
   ;; the form `(list-type . list-size)`. If nil then it is disabled.
   ;; Possible values for list-type are:
   ;; `recents' `recents-by-project' `bookmarks' `projects' `agenda' `todos'.
   ;; List sizes may be nil, in which case
   ;; `spacemacs-buffer-startup-lists-length' takes effect.
   ;; The exceptional case is `recents-by-project', where list-type must be a
   ;; pair of numbers, e.g. `(recents-by-project . (7 .  5))', where the first
   ;; number is the project limit and the second the limit on the recent files
   ;; within a project.
   dotspacemacs-startup-lists '((recents . 8)
                                (projects . 5)
                                (bookmarks . 5))

   ;; True if the home buffer should respond to resize events. (default t)
   dotspacemacs-startup-buffer-responsive t

   ;; Show numbers before the startup list lines. (default t)
   dotspacemacs-show-startup-list-numbers t

   ;; The minimum delay in seconds between number key presses. (default 0.4)
   dotspacemacs-startup-buffer-multi-digit-delay 0.4

   ;; If non-nil, show file icons for entries and headings on Spacemacs home buffer.
   ;; This has no effect in terminal or if "all-the-icons" package or the font
   ;; is not installed. (default nil)
   dotspacemacs-startup-buffer-show-icons nil

   ;; Default major mode for a new empty buffer. Possible values are mode
   ;; names such as `text-mode'; and `nil' to use Fundamental mode.
   ;; (default `text-mode')
   dotspacemacs-new-empty-buffer-major-mode 'text-mode

   ;; Default major mode of the scratch buffer (default `text-mode')
   dotspacemacs-scratch-mode 'emacs-lisp-mode

   ;; If non-nil, *scratch* buffer will be persistent. Things you write down in
   ;; *scratch* buffer will be saved and restored automatically.
   dotspacemacs-scratch-buffer-persistent t

   ;; If non-nil, `kill-buffer' on *scratch* buffer
   ;; will bury it instead of killing.
   dotspacemacs-scratch-buffer-unkillable t

   ;; Initial message in the scratch buffer, such as "Welcome to Spacemacs!"
   ;; (default nil)
   dotspacemacs-initial-scratch-message nil

   ;; List of themes, the first of the list is loaded when spacemacs starts.
   ;; Press `SPC T n' to cycle to the next theme in the list (works great
   ;; with 2 themes variants, one dark and one light)
   dotspacemacs-themes '(
                         ef-autumn
                         ef-winter
                         farmhouse-light
                         farmhouse-dark
                         dakrone
                         hc-zenburn
                         leuven
                         cyberpunk
                         gruvbox-light-hard
                         gruvbox-dark-hard
                         )

   ;; Set the theme for the Spaceline. Supported themes are `spacemacs',
   ;; `all-the-icons', `custom', `doom', `vim-powerline' and `vanilla'. The
   ;; first three are spaceline themes. `doom' is the doom-emacs mode-line.
   ;; `vanilla' is default Emacs mode-line. `custom' is a user defined themes,
   ;; refer to the DOCUMENTATION.org for more info on how to create your own
   ;; spaceline theme. Value can be a symbol or list with additional properties.
   ;; (default '(spacemacs :separator wave :separator-scale 1.5))
   dotspacemacs-mode-line-theme '(spacemacs :separator curve)

   ;; If non-nil the cursor color matches the state color in GUI Emacs.
   ;; (default t)
   dotspacemacs-colorize-cursor-according-to-state t

   ;; Default font or prioritized list of fonts. The `:size' can be specified as
   ;; a non-negative integer (pixel size), or a floating-point (point size).
   ;; Point size is recommended, because it's device independent. (default 10.0)
   dotspacemacs-default-font '(
                               ("FiraCode Nerd Font"
                                :size 18.0
                                :weight normal
                                :width normal)
                               ("MesloLGS Nerd Font Mono"
                                :size 18.0
                                :weight normal
                                :width normal)
                               ("Inconsolata Nerd Font"
                                :size 18.0
                                :weight normal
                                :width normal)
                               ("Cascadia Mono NF"
                                :size 18.0
                                :weight normal
                                :width normal)
                               ("JetBrainsMono Nerd Font"
                                :size 18.0
                                :weight normal
                                :width normal)
                               ("Monoid Nerd Font"
                                :size 18.0
                                :weight normal
                                :width normal)
                               ("VictorMono Nerd Font"
                                :size 18.0
                                :weight normal
                                :width normal)
                               ("Iosevka Nerd Font"
                                :size 18.0
                                :weight normal
                                :width normal)
                               ("Cousine Nerd Font"
                                :size 18.0
                                :weight normal
                                :width normal)
                               ("IMWritingMonoS Nerd Font"
                                :size 18.0
                                :weight normal
                                :width normal)
                               ("Hack Nerd Font"
                               :size 18.0
                               :weight normal
                               :width normal)
                               ("Hack"
                                :size 18.0
                                :weight normal
                                :width normal)
                               ("MesloLGS NF"
                                :size 18.0
                                :weight normal
                                :width normal)
                               ("SauceCodePro Nerd Font"
                                :size 18.0
                                :weight normal
                                :width normal)
                               
                               )

   ;; The leader key (default "SPC")
   dotspacemacs-leader-key "SPC"

   ;; The key used for Emacs commands `M-x' (after pressing on the leader key).
   ;; (default "SPC")
   dotspacemacs-emacs-command-key "SPC"

   ;; The key used for Vim Ex commands (default ":")
   dotspacemacs-ex-command-key ":"

   ;; The leader key accessible in `emacs state' and `insert state'
   ;; (default "M-m")
   dotspacemacs-emacs-leader-key "M-m"

   ;; Major mode leader key is a shortcut key which is the equivalent of
   ;; pressing `<leader> m`. Set it to `nil` to disable it. (default ",")
   dotspacemacs-major-mode-leader-key ","

   ;; Major mode leader key accessible in `emacs state' and `insert state'.
   ;; (default "C-M-m" for terminal mode, "<M-return>" for GUI mode).
   ;; Thus M-RET should work as leader key in both GUI and terminal modes.
   ;; C-M-m also should work in terminal mode, but not in GUI mode.
   dotspacemacs-major-mode-emacs-leader-key (if window-system "<M-return>" "C-M-m")

   ;; These variables control whether separate commands are bound in the GUI to
   ;; the key pairs `C-i', `TAB' and `C-m', `RET'.
   ;; Setting it to a non-nil value, allows for separate commands under `C-i'
   ;; and TAB or `C-m' and `RET'.
   ;; In the terminal, these pairs are generally indistinguishable, so this only
   ;; works in the GUI. (default nil)
   dotspacemacs-distinguish-gui-tab t

   ;; Name of the default layout (default "Default")
   dotspacemacs-default-layout-name "Default"

   ;; If non-nil the default layout name is displayed in the mode-line.
   ;; (default nil)
   dotspacemacs-display-default-layout nil

   ;; If non-nil then the last auto saved layouts are resumed automatically upon
   ;; start. (default nil)
   dotspacemacs-auto-resume-layouts nil

   ;; If non-nil, auto-generate layout name when creating new layouts. Only has
   ;; effect when using the "jump to layout by number" commands. (default nil)
   dotspacemacs-auto-generate-layout-names t

   ;; Size (in MB) above which spacemacs will prompt to open the large file
   ;; literally to avoid performance issues. Opening a file literally means that
   ;; no major mode or minor modes are active. (default is 1)
   dotspacemacs-large-file-size 1

   ;; Location where to auto-save files. Possible values are `original' to
   ;; auto-save the file in-place, `cache' to auto-save the file to another
   ;; file stored in the cache directory and `nil' to disable auto-saving.
   ;; (default 'cache)
   dotspacemacs-auto-save-file-location 'cache

   ;; Maximum number of rollback slots to keep in the cache. (default 5)
   dotspacemacs-max-rollback-slots 5

   ;; If non-nil, the paste transient-state is enabled. While enabled, after you
   ;; paste something, pressing `C-j' and `C-k' several times cycles through the
   ;; elements in the `kill-ring'. (default nil)
   dotspacemacs-enable-paste-transient-state t

   ;; Which-key delay in seconds. The which-key buffer is the popup listing
   ;; the commands bound to the current keystroke sequence. (default 0.4)
   dotspacemacs-which-key-delay 0.4

   ;; Which-key frame position. Possible values are `right', `bottom' and
   ;; `right-then-bottom'. right-then-bottom tries to display the frame to the
   ;; right; if there is insufficient space it displays it at the bottom.
   ;; (default 'bottom)
   dotspacemacs-which-key-position 'bottom

   ;; Control where `switch-to-buffer' displays the buffer. If nil,
   ;; `switch-to-buffer' displays the buffer in the current window even if
   ;; another same-purpose window is available. If non-nil, `switch-to-buffer'
   ;; displays the buffer in a same-purpose window even if the buffer can be
   ;; displayed in the current window. (default nil)
   dotspacemacs-switch-to-buffer-prefers-purpose nil

   ;; If non-nil a progress bar is displayed when spacemacs is loading. This
   ;; may increase the boot time on some systems and emacs builds, set it to
   ;; nil to boost the loading time. (default t)
   dotspacemacs-loading-progress-bar t

   ;; If non-nil the frame is fullscreen when Emacs starts up. (default nil)
   ;; (Emacs 24.4+ only)
   dotspacemacs-fullscreen-at-startup nil

   ;; If non-nil `spacemacs/toggle-fullscreen' will not use native fullscreen.
   ;; Use to disable fullscreen animations in OSX. (default nil)
   dotspacemacs-fullscreen-use-non-native nil

   ;; If non-nil the frame is maximized when Emacs starts up.
   ;; Takes effect only if `dotspacemacs-fullscreen-at-startup' is nil.
   ;; (default nil) (Emacs 24.4+ only)
   dotspacemacs-maximized-at-startup nil

   ;; If non-nil the frame is undecorated when Emacs starts up. Combine this
   ;; variable with `dotspacemacs-maximized-at-startup' in OSX to obtain
   ;; borderless fullscreen. (default nil)
   dotspacemacs-undecorated-at-startup nil

   ;; A value from the range (0..100), in increasing opacity, which describes
   ;; the transparency level of a frame when it's active or selected.
   ;; Transparency can be toggled through `toggle-transparency'. (default 90)
   dotspacemacs-active-transparency 90

   ;; A value from the range (0..100), in increasing opacity, which describes
   ;; the transparency level of a frame when it's inactive or deselected.
   ;; Transparency can be toggled through `toggle-transparency'. (default 90)
   dotspacemacs-inactive-transparency 90

   ;; If non-nil show the titles of transient states. (default t)
   dotspacemacs-show-transient-state-title t

   ;; If non-nil show the color guide hint for transient state keys. (default t)
   dotspacemacs-show-transient-state-color-guide t

   ;; If non-nil unicode symbols are displayed in the mode line.
   ;; If you use Emacs as a daemon and wants unicode characters only in GUI set
   ;; the value to quoted `display-graphic-p'. (default t)
   dotspacemacs-mode-line-unicode-symbols t

   ;; If non-nil smooth scrolling (native-scrolling) is enabled. Smooth
   ;; scrolling overrides the default behavior of Emacs which recenters point
   ;; when it reaches the top or bottom of the screen. (default t)
   dotspacemacs-smooth-scrolling t

   ;; Show the scroll bar while scrolling. The auto hide time can be configured
   ;; by setting this variable to a number. (default t)
   dotspacemacs-scroll-bar-while-scrolling t

   ;; Control line numbers activation.
   ;; If set to `t', `relative' or `visual' then line numbers are enabled in all
   ;; `prog-mode' and `text-mode' derivatives. If set to `relative', line
   ;; numbers are relative. If set to `visual', line numbers are also relative,
   ;; but only visual lines are counted. For example, folded lines will not be
   ;; counted and wrapped lines are counted as multiple lines.
   ;; This variable can also be set to a property list for finer control:
   ;; '(:relative nil
   ;;   :visual nil
   ;;   :disabled-for-modes dired-mode
   ;;   :size-limit-kb 1000)
   ;; When used in a plist, `visual' takes precedence over `relative'.
   ;; (default nil)
   dotspacemacs-line-numbers '(:relative nil
                              :visible t
                              :disabled-for-modes dired-mode
                                                  doc-view-mode
                                                  markdown-mode
                                                  pdf-view-mode
                                                  text-mode
                                                  xml-mode
                                                  sgml-mode
                              :size-limit-kb 1000)
   ;; dotspacemacs-line-numbers nil

   ;; Code folding method. Possible values are `evil', `origami' and `vimish'.
   ;; (default 'evil)
   dotspacemacs-folding-method 'evil

   ;; If non-nil and `dotspacemacs-activate-smartparens-mode' is also non-nil,
   ;; `smartparens-strict-mode' will be enabled in programming modes.
   ;; (default nil)
   dotspacemacs-smartparens-strict-mode nil

   ;; If non-nil smartparens-mode will be enabled in programming modes.
   ;; (default t)
   dotspacemacs-activate-smartparens-mode t

   ;; If non-nil pressing the closing parenthesis `)' key in insert mode passes
   ;; over any automatically added closing parenthesis, bracket, quote, etc...
   ;; This can be temporary disabled by pressing `C-q' before `)'. (default nil)
   dotspacemacs-smart-closing-parenthesis nil

   ;; Select a scope to highlight delimiters. Possible values are `any',
   ;; `current', `all' or `nil'. Default is `all' (highlight any scope and
   ;; emphasis the current one). (default 'all)
   dotspacemacs-highlight-delimiters 'all

   ;; If non-nil, start an Emacs server if one is not already running.
   ;; (default nil)
   dotspacemacs-enable-server t

   ;; Set the emacs server socket location.
   ;; If nil, uses whatever the Emacs default is, otherwise a directory path
   ;; like \"~/.emacs.d/server\". It has no effect if
   ;; `dotspacemacs-enable-server' is nil.
   ;; (default nil)
   ;; dotspacemacs-server-socket-dir "~/.emacs.d/server"
   dotspacemacs-server-socket-dir nil

   ;; If non-nil, advise quit functions to keep server open when quitting.
   ;; (default nil)
   dotspacemacs-persistent-server nil

   ;; List of search tool executable names. Spacemacs uses the first installed
   ;; tool of the list. Supported tools are `rg', `ag', `pt', `ack' and `grep'.
   ;; (default '("rg" "ag" "pt" "ack" "grep"))
   dotspacemacs-search-tools '("rg" "ag" "pt" "ack" "grep")

   ;; Format specification for setting the frame title.
   ;; %a - the `abbreviated-file-name', or `buffer-name'
   ;; %t - `projectile-project-name'
   ;; %I - `invocation-name'
   ;; %S - `system-name'
   ;; %U - contents of $USER
   ;; %b - buffer name
   ;; %f - visited file name
   ;; %F - frame name
   ;; %s - process status
   ;; %p - percent of buffer above top of window, or Top, Bot or All
   ;; %P - percent of buffer above bottom of window, perhaps plus Top, or Bot or All
   ;; %m - mode name
   ;; %n - Narrow if appropriate
   ;; %z - mnemonics of buffer, terminal, and keyboard coding systems
   ;; %Z - like %z, but including the end-of-line format
   ;; If nil then Spacemacs uses default `frame-title-format' to avoid
   ;; performance issues, instead of calculating the frame title by
   ;; `spacemacs/title-prepare' all the time.
   ;; (default "%I@%S")
   dotspacemacs-frame-title-format "%I | %t | %f %n"

   ;; Format specification for setting the icon title format
   ;; (default nil - same as frame-title-format)
   dotspacemacs-icon-title-format nil

   ;; Show trailing whitespace (default t)
   dotspacemacs-show-trailing-whitespace t

   ;; Delete whitespace while saving buffer. Possible values are `all'
   ;; to aggressively delete empty line and long sequences of whitespace,
   ;; `trailing' to delete only the whitespace at end of lines, `changed' to
   ;; delete only whitespace for changed lines or `nil' to disable cleanup.
   ;; (default nil)
   dotspacemacs-whitespace-cleanup nil

   ;; If non-nil activate `clean-aindent-mode' which tries to correct
   ;; virtual indentation of simple modes. This can interfere with mode specific
   ;; indent handling like has been reported for `go-mode'.
   ;; If it does deactivate it here.
   ;; (default t)
   dotspacemacs-use-clean-aindent-mode t

   ;; Accept SPC as y for prompts if non-nil. (default nil)
   dotspacemacs-use-SPC-as-y nil

   ;; If non-nil shift your number row to match the entered keyboard layout
   ;; (only in insert state). Currently supported keyboard layouts are:
   ;; `qwerty-us', `qwertz-de' and `querty-ca-fr'.
   ;; New layouts can be added in `spacemacs-editing' layer.
   ;; (default nil)
   dotspacemacs-swap-number-row nil

   ;; Either nil or a number of seconds. If non-nil zone out after the specified
   ;; number of seconds. (default nil)
   dotspacemacs-zone-out-when-idle nil

   ;; Run `spacemacs/prettify-org-buffer' when
   ;; visiting README.org files of Spacemacs.
   ;; (default nil)
   dotspacemacs-pretty-docs nil

   ;; If nil the home buffer shows the full path of agenda items
   ;; and todos. If non-nil only the file name is shown.
   dotspacemacs-home-shorten-agenda-source nil

   ;; If non-nil then byte-compile some of Spacemacs files.
   dotspacemacs-byte-compile nil))
(defun dotspacemacs/user-env ()
  "Environment variables setup.
This function defines the environment variables for your Emacs session. By
default it calls `spacemacs/load-spacemacs-env' which loads the environment
variables declared in `~/.spacemacs.env' or `~/.spacemacs.d/.spacemacs.env'.
See the header of this file for more information."
  (spacemacs/load-spacemacs-env))
  (defun dotspacemacs/user-init ()
    "Initialization for user code:
  This function is called immediately after `dotspacemacs/init', before layer
  configuration.
  It is mostly for variables that should be set before packages are loaded.
  If you are unsure, try setting them in `dotspacemacs/user-config' first."

    ;; add the private directory
    (add-to-list 'load-path "/Users/rodk/.emacs.d/private/")

    (require 'asdf)
    (asdf-enable)

    ;; (require 'chatgpt)

    (load-file "/Users/rodk/.emacs.d/private/local/narrow-indirect.el")


    (defun file-notify-rm-all-watches ()
      "Remove all existing file notification watches from Emacs."
      (interactive)
      (maphash
       (lambda (key _value)
         (file-notify-rm-watch key))
       file-notify-descriptors)))
(setq comp-deferred-compilation t)
  
(defun dotspacemacs/user-load ()
  "Library to load while dumping.
This function is called only while dumping Spacemacs configuration. You can
`require' or `load' the libraries of your choice that will be included in the
dump."
  )
(defun dotspacemacs/user-config ()
  "Configuration for user code:
This function is called at the very end of Spacemacs startup, after layer
configuration.
Put your configuration code here, except for variables that should be set
before packages are loaded."
  (setq custom-file "~/.spacemacs.d/custom.el")
  (load "~/github/editWithEmacs.spoon/hammerspoon.el")
  (defun codelahoma/set-font-size-based-on-screen ()
    (let ((screen-width (display-pixel-width))
          (screen-height (display-pixel-height)))
      (cond
       ((and (> screen-width 1920) (> screen-height 1080))
        (set-face-attribute 'default nil :height 180))  ;; Large screen
       ((and (> screen-width 1366) (> screen-height 900))
        (set-face-attribute 'default nil :height 160))   ;; Medium screen
       (t
        (set-face-attribute 'default nil :height 120))   ;; Small screen
       )))
  
  (add-hook 'window-setup-hook 'codelahoma/set-font-size-based-on-screen)
  (custom-set-faces
   '(company-tooltip-common
     ((t (:inherit company-tooltip :weight bold :underline nil))))
   '(company-tooltip-common-selection
     ((t (:inherit company-tooltip-selection :weight bold :underline nil)))))
  (use-package evil-easymotion
    :init (evilem-default-keybindings "\\"))
  (advice-add 'evil-avy-goto-line :after #'evil-scroll-line-to-center)
  (advice-add 'evil-ex-search-next :after #'evil-scroll-line-to-center)
  (advice-add 'evil-avy-goto-char-timer :after #'evil-scroll-line-to-center)
  (advice-add 'better-jumper-jump-backward :after #'evil-scroll-line-to-center)
  (advice-add 'better-jumper-jump-forward :after #'evil-scroll-line-to-center)
  (add-hook 'bookmark-after-jump-hook 'evil-scroll-line-to-center)
  (font-lock-add-keywords 'python-mode
                          '(("\\(lambda\\) " 
                             (0 (prog1 ()
                                  (compose-region
                                   (match-beginning 1)
                                   (match-end 1)
                                   "λ"))))))
  
  (let* ((variable-tuple
          (cond
           ((x-list-fonts "Source Sans Pro") '(:font "Source Sans Pro"))
           ((x-list-fonts "Avenir Next") '(:font "Avenir Next"))
           ((x-list-fonts "Verdana")         '(:font "Verdana"))
           ;; ((x-list-fonts "Fira Sans")       '(:font "Fira Sans"))
           ((x-list-fonts "ETBembo") '(:font "ETBembo"))
           ((x-list-fonts "Lucida Grande")   '(:font "Lucida Grande"))
           ((x-family-fonts "Sans Serif")    '(:family "Sans Serif"))
           (nil (warn "Cannot find a Sans Serif Font.  Install Source Sans Pro."))))
         (headline           `(:inherit default :weight normal ))
         )
  
    (custom-theme-set-faces
     'user
     '(fixed-pitch ((t ( :family "FiraMono Nerd Font" :height 1.0))))
     '(variable-pitch ((t (:family "Source Sans Pro" :height 1.1))))
     ;; Org appearance configuration moved to codelahoma-org.org
     ))
  ;; Org color scheme configuration moved to codelahoma-org.org
  (with-eval-after-load 'org-superstar
    (setq org-superstar-item-bullet-alist
          '((?* . ?•)
            (?+ . ?➤)
            (?- . ?•)))
    (setq org-superstar-headline-bullets-list
          '("⦿" "⬦" "○" "▷"))
    (setq org-superstar-special-todo-items t)
    (setq org-superstar-remove-leading-stars t)
    ;; Enable custom bullets for TODO items
    (setq org-superstar-todo-bullet-alist
          '(("TODO" . ?🔳)
            ("NEXT" . ?👀)
            ("IN-PROGRESS" . ?🚀)
            ("CODE-COMPLETE" . ?💾)
            ("NEEDS-REFINEMENT" . ?🔍)
            ("NOT-APPLICABLE" . ?💩)
            ("WAITING" . ?☕)
            ("QUESTION" . ?❓)
            ("MEETING" . ?⏰)
            ("CANCELLED" . ?❌)
            ("ATTENDED" . ?📝)
            ("ANSWERED" . ?👍) 
            ("DONE" . ?✅)))
    (org-superstar-restart))
  ;; Set default bullet scheme - now handled by codelahoma-org extensions
  (with-eval-after-load 'org-superstar
    (when (fboundp 'rk/switch-org-bullets)
      (rk/switch-org-bullets "Runes")))
  (defun rk/validate-xml-with-xmllint ()
    "Validate the current XML file using xmllint and create a compilation-style error buffer."
    (interactive)
    (let* ((xml-file (buffer-file-name))
           (xsd-file "/Users/rodk/work/atlas-up-ai/atlas_up/ai/prompts/xml/complete-llm-schema.xsd")  ; Replace with path to your XSD
           (buffer-name "*XML Validation*")
           (error-regexp
            '("^\\(/.*\\.xml\\):\\([0-9]+\\): .*$" 1 2))
           (command (format "xmllint --noout --schema %s %s 2>&1"
                            (shell-quote-argument xsd-file)
                            (shell-quote-argument xml-file))))
  
      ;; Kill existing validation buffer if it exists
      (when (get-buffer buffer-name)
        (kill-buffer buffer-name))
  
      ;; Run command and capture output
      (with-current-buffer (get-buffer-create buffer-name)
        (erase-buffer)
        (insert (shell-command-to-string command))
  
        ;; Set compilation mode to enable error jumping
        (compilation-mode)
  
        ;; Add error regexp for XML validation errors
        (set (make-local-variable 'compilation-error-regexp-alist-alist)
             (list (cons 'xml-error error-regexp)))
        (set (make-local-variable 'compilation-error-regexp-alist)
             '(xml-error))
  
        ;; Show the buffer
        (display-buffer (current-buffer))
  
        ;; If no errors, close the buffer after a short delay
        (if (= (buffer-size) 0)
            (progn
              (message "XML validation successful!")
              (run-at-time 2 nil
                           (lambda ()
                             (when (get-buffer buffer-name)
                               (kill-buffer buffer-name)))))
          (message "XML validation failed. Check *XML Validation* buffer.")))))
  ;; (require 'python)
  ;; (setq chatgpt-repo-path (expand-file-name "chatgpt/" quelpa-build-dir))
  ;; (global-set-key (kbd "C-c q") #'chatgpt-query)
  (require 'gptel)
  (require 'gptel-extensions)
  (setq gptel-default-mode 'org-mode)
  
  (defun rk/gptel-before-advice (&rest args)
    "Before advice for =gptel' function. Sets =api-key= parameter
  from =auth-source-search' results."
    (let ((auth-info (nth 0 (auth-source-search :host "openai.com"))))
      (setq-local gptel-api-key (plist-get auth-info :secret))))
  
  (advice-add 'gptel :before #'rk/gptel-before-advice)
  (add-hook 'find-file-hook 'direnv-update-directory-environment)
  
  (with-eval-after-load 'company
    ;; disable inline previews
    (delq 'company-preview-if-just-one-frontend company-frontends))
  
  ;; (with-eval-after-load 'copilot
  ;;   (define-key copilot-completion-map (kbd "<tab>") 'copilot-accept-completion)
  ;;   (define-key copilot-completion-map (kbd "TAB") 'copilot-accept-completion)
  ;;   (define-key copilot-completion-map (kbd "C-<tab>") 'copilot-accept-completion-by-word)
  ;;   (define-key copilot-completion-map (kbd "C-TAB") 'copilot-accept-completion-by-word))
  
  ;; (add-hook 'prog-mode-hook 'copilot-mode)
  (with-eval-after-load 'elfeed
    (require 'elfeed)
    
    (defun elfeed-save-to-org-roam-dailies ()
      "Save the current elfeed entry to org-roam dailies."
      (interactive)
      (let* ((entry (elfeed-search-selected :single))
             (title (elfeed-entry-title entry))
             (link (elfeed-entry-link entry))
             (content (elfeed-deref (elfeed-entry-content entry)))
             (date (format-time-string "%Y-%m-%d"))
             (org-roam-dailies-dir (expand-file-name "dailies" org-roam-directory))
             (daily-file (expand-file-name (concat date ".org") org-roam-dailies-dir)))
        (unless (file-exists-p daily-file)
          (with-temp-buffer (write-file daily-file)))
        (with-current-buffer (find-file-noselect daily-file)
          (goto-char (point-max))
          (insert (concat "* " title "\n"))
          (insert (concat "[[" link "][" link "]]\n\n"))
          (insert (concat content "\n"))
          (save-buffer))))
  
    ;; Bind the function to a key for easy access
    (define-key elfeed-search-mode-map (kbd "o") 'elfeed-save-to-org-roam-dailies))
  
  ;; ;; Enable Vertico globally
  ;; ;; (vertico-mode 1)
  
  ;; ;; Enable Marginalia annotations
  ;; (marginalia-mode 2)
  
  ;; ;; Configure Orderless matching
  ;; (with-eval-after-load 'orderless
  ;;   (setq completion-styles '(orderless)
  ;;         completion-category-overrides '((file (styles . (partial-completion))))))
  
  ;; ;; Embark key bindings
  ;; (global-set-key (kbd "C-.") #'embark-act)        ;; Act on candidate
  ;; (global-set-key (kbd "C-,") #'embark-dwim)      ;; Default action
  ;; (setq embark-action-indicator
  ;;       (lambda (map) (which-key--show-keymap "Embark Actions" map nil nil 'no-paging))
  ;;       embark-become-indicator embark-action-indicator)
  
  ;; ;; Corfu configuration
  ;; (setq corfu-auto t                  ;; Enable auto-popup
  ;;       corfu-cycle t)                ;; Allow cycling through candidates
  ;; (global-corfu-mode 1)
  
  ;; ;; Additional Consult settings
  ;; (setq consult-narrow-key "<")       ;; Narrowing prefix key
  ;; (setq consult-project-root-function #'projectile-project-root) ;; Use Projectile for root detection
   (defun my-info-mode-hook ()
     (local-set-key (kbd "n") 'Info-next)
     (local-set-key (kbd "p") 'Info-prev)
     (local-set-key (kbd "u") 'Info-up)
     (local-set-key (kbd "m") 'Info-menu)
     (local-set-key (kbd "s") 'Info-search)
     (local-set-key (kbd "f") 'Info-follow-nearest-node))
  
   (add-hook 'Info-mode-hook 'my-info-mode-hook)
  
  
  
   ;; ;; Bind the function to a key for easy access
   (defun renumber-region (start end)
     "Renumber the lines in the region from START to END."
     (interactive "r")
     (let ((line-number 1))
       (goto-char start)
       (while (and (< (point) end) (not (eobp)))
         (if (re-search-forward "^\\([0-9]+\\)\\(\\..*\\)$" (line-end-position) t)
             (replace-match (format "%d\\2" line-number))
           (forward-line 1))
         (setq line-number (1+ line-number))
         (forward-line 1))))
  
   (global-set-key (kbd "C-c r") 'renumber-region)
   (setq helm-ag-use-grep-ignore-list nil)
   (defun insert-current-date-time ()
     "Insert the current date and time."
     (interactive)
     (insert (format-time-string "%Y-%m-%d %H:%M:%S")))
  
   (spacemacs/set-leader-keys "otd" 'insert-current-date-time)
  (global-set-key (kbd "C-c C-x C-c") 'org-copy-current-source-block)
  (defun rk/insert-spacemacs-config-block ()
  "Insert org-babel source block for Spacemacs config."
  (interactive)
  (let* ((targets (rk/get-spacemacs-config-targets))
         (target (completing-read "Choose target or specify new: " targets nil t)))
    (setq rk/last-inserted-config-target target)
    (insert (format "#+begin_src emacs-lisp :noweb-ref %s\n\n" target)
            (format "  ;; insert your code here\n\n")
            "#+end_src\n")))
  
  (defun rk/get-spacemacs-config-targets ()
    "Get list of unique Spacemacs config targets from noweb references in source blocks with matching header."
    (interactive)
    (let ((targets '()))
      (save-excursion
        (goto-char (point-min))
        (while (re-search-forward "^#\\+begin_src emacs-lisp :noweb-ref \\([^,[:space:]]+\\)[,[:space:]]" nil t)
          (let ((target (match-string 1)))
            (unless (member target targets)
              (push target targets)))))
      targets))
  
  (global-set-key (kbd "C-c i") #'rk/insert-spacemacs-config-block)
  (defun codelahoma/insert-random-uid ()
    (interactive)
    (shell-command "printf %s \"$(uuidgen)\"" t))
  ;; Load CodeLahoma Org Extensions (centralized org configuration)
  (with-eval-after-load 'org
    (let ((codelahoma-org-file (expand-file-name "~/.spacemacs.d/codelahoma-org.el")))
      (when (file-exists-p codelahoma-org-file)
        (load-file codelahoma-org-file)
        (message "Loaded CodeLahoma org extensions from %s" codelahoma-org-file))))          ; Collects all general :noweb-ref user-config blocks
  (spacemacs/declare-prefix "ob" "buffer")
  (spacemacs/set-leader-keys "obn" 'spacemacs/new-empty-buffer)
  
  (spacemacs/declare-prefix "oc" "copy")
  (spacemacs/set-leader-keys "ocl" 'avy-copy-line)
  (spacemacs/set-leader-keys "ocp" 'forge-copy-url-at-point-as-kill)
  
  (spacemacs/declare-prefix "ox" "text")
  (spacemacs/set-leader-keys "oxw" 'white-space-cleanup)
  
  (spacemacs/declare-prefix "oh" "Hammerspoon")
  (spacemacs/set-leader-keys "ohr" 'rk/reset-hammerspoon) ; Ensure rk/reset-hammerspoon is defined elsewhere (e.g. user-config)
  
  (spacemacs/declare-prefix "oC" "Claude")
  (spacemacs/set-leader-keys "oCC" 'rk/clip-for-claude) ; Ensure rk/clip-for-claude is defined elsewhere (e.g. user-config)
  
  ;; System clipboard integration for visual state
  (define-key evil-visual-state-map (kbd "s-c") (kbd "\"+y"))
  (define-key evil-visual-state-map (kbd "s-v") (kbd "\"+p"))
  
  ;; Override default Spacemacs frame killer or add alias
  (evil-leader/set-key "q q" 'spacemacs/frame-killer)
  
  ;; If you intend to use this, uncomment and ensure rk/helm-files-do-rg is defined elsewhere
  ;; (evil-leader/set-key "/" 'rk/helm-files-do-rg)
  (spacemacs/declare-prefix "of" "folding")
  (spacemacs/set-leader-keys
    "off" 'fold-this
    "ofm" 'fold-this-all
    "ofr" 'fold-this-unfold-all)
  (spacemacs/declare-prefix "oa" "applications")
  (spacemacs/set-leader-keys
    "oap" 'pinboard); <<<--- ADD THIS LINE HERE
            ; Collects the remaining to-organize block

  (when (file-exists-p custom-file)
    (load-file custom-file)))
